[develop]
script_dir=$base/lib/natural_language_commander
[install]
install_scripts=$base/lib/natural_language_commander
[build_scripts]
executable=/usr/bin/env python3
# executable = /home/brad/AI_hand/.venv/bin/python

[options]
packages = find:
install_requires =
    rclpy
    numpy
    sounddevice
    soundfile
    groq>=0.4.0
    duckduckgo-search
